namespace Client
{

    using System.Collections.Generic;
    using System.Linq;
    using System;

    public class Toppings
    {

        private static readonly Random Random = new Random();
        public static IEnumerable<string> Select(int select)
        {
            return Values.OrderBy(x => Random.Next()).Take(select);
        }
        static readonly string[] Values = new string[]{
            "Alfalfa Sprouts",
            "Artichoke hearts",
            "Avocado",
            "Baby leeks",
            "Beetroot",
            "Black Beans",
            "Broccoli",
            "Capers",
            "Capicolla",
            "Carrot",
            "Cherry tomatoes",
            "Dried tomatoes",
            "Eggplant",
            "Fungi",
            "Fungi carciofi",
            "Green peppers",
            "Kalamata olives",
            "Lettuce",
            "Mushrooms",
            "Onions",
            "Olives",
            "Peas",
            "Porcini mushrooms",
            "Portobello Mushrooms",
            "Red beans",
            "Red onions",
            "Red peppers",
            "Roast cauliflower",
            "Roasted eggplant",
            "Roasted Garlic",
            "Roasted peppers",
            "scallions",
            "Shallots",
            "Snow peas",
            "Spinach",
            "Sun dried tomatoes",
            "Sweet corn",
            "Watercress",
            "Wild mushrooms",
            "Yellow peppers",
            "Yellow squash",
            "Zucchini",
            "Almonds",
            "Peanuts",
            "Pistachios",
            "Pecans",
            "Pine Nuts",
            "Walnuts",
            "Basil",
            "Bay Leaf",
            "Cardamon",
            "Chili Dried or Fresh",
            "Chives",
            "Cilantro",
            "Coriander",
            "Cumin",
            "Dill",
            "Garlic",
            "Jalapeno Peppers",
            "Laurel",
            "Marjoram",
            "Methi Leaves (aka Fenugreek)",
            "Oregano",
            "Parley",
            "Pepper",
            "Rosemary",
            "Basil",
            "Bay Leaf",
            "Cardamon",
            "Anchovies",
            "Cajun Prawn",
            "Crayfish",
            "Lobster",
            "Oysters",
            "Prawns",
            "Salmon",
            "Shrimps",
            "Smoked Salmon",
            "Squid",
            "Tuna",
            "Whitebait",
            "Blue Cheese",
            "Brie",
            "Camembert",
            "Chedar",
            "Colby",
            "Feta",
            "Goat Cheese",
            "Gorgonzola",
            "Limburger",
            "Manchego",
            "Monterey Jack",
            "Parmesan",
            "Mozzarella",
            "Muenster",
            "Port de Salut",
            "Provolone",
            "Ricota",
            "Romano",
            "Roquefort",
            "Smoked Gouda",
            "Bacon",
            "BBQ Chicken",
            "Beef",
            "Cajun Chicken",
            "Chicken Masala",
            "Chicken Tikka",
            "Chorizo",
            "Duck",
            "Ham",
            "Honey Cured Ham",
            "Meatballs",
            "Pepperoni",
            "Proscuitto",
            "Salami",
            "Sausage",
            "Serrano Ham",
            "Turkey",
            "Venison",
        };
    }

    public class Customer
    {
        public string CustomerName { get; set; }
        public string Address { get; set; }

        public static Customer[] Customers = new Customer[] {
            new Customer { CustomerName = "Leonard Le", Address = "399-4801 Odio. Street" },
            new Customer { CustomerName = "Anjolie W. Odonnell", Address = "194-4933 Eu Av." },
            new Customer { CustomerName = "Murphy Berger", Address = "319-7370 Vel St." },
            new Customer { CustomerName = "Anika J. Benjamin", Address = "Ap #843-1254 Suspendisse St." },
            new Customer { CustomerName = "Austin E. Horton", Address = "Ap #544-6499 Et Street" },
            new Customer { CustomerName = "Kieran A. Salazar", Address = "Ap #668-930 Ornare Rd." },
            new Customer { CustomerName = "Maggy Trevino", Address = "Ap #191-5732 Non Rd." },
            new Customer { CustomerName = "Blaze Z. Baker", Address = "P.O. Box 573, 8759 Donec St." },
            new Customer { CustomerName = "Calista E. Bradley", Address = "P.O. Box 568, 4854 Lacus. Avenue" },
            new Customer { CustomerName = "Bertha Z. Walls", Address = "P.O. Box 940, 294 Pellentesque St." },
            new Customer { CustomerName = "Quinlan Mcneil", Address = "P.O. Box 391, 2789 Diam Rd." },
            new Customer { CustomerName = "Troy I. Richard", Address = "Ap #666-575 Semper Ave" },
            new Customer { CustomerName = "Griffin Bauer", Address = "P.O. Box 586, 7874 Aliquet Avenue" },
            new Customer { CustomerName = "Faith V. Harrell", Address = "4803 Aliquet St." },
            new Customer { CustomerName = "Octavia D. Andrews", Address = "P.O. Box 566, 2868 Non St." },
            new Customer { CustomerName = "Indigo Bell", Address = "314-5528 Ornare. Avenue" },
            new Customer { CustomerName = "Hunter Rutledge", Address = "P.O. Box 579, 5640 Neque St." },
            new Customer { CustomerName = "Zeph U. Deleon", Address = "487-6921 Egestas St." },
            new Customer { CustomerName = "Daria O. Huffman", Address = "7385 Sit Road" },
            new Customer { CustomerName = "Cruz U. Nixon", Address = "P.O. Box 317, 7382 Curae; Ave" },
            new Customer { CustomerName = "Rafael U. Poole", Address = "P.O. Box 837, 7770 Iaculis Ave" },
            new Customer { CustomerName = "Zenaida Cobb", Address = "3630 Porttitor Street" },
            new Customer { CustomerName = "Emerson C. Sampson", Address = "Ap #808-5449 Eu St." },
            new Customer { CustomerName = "Justin F. Thomas", Address = "835-6511 Non St." },
            new Customer { CustomerName = "Lynn Drake", Address = "P.O. Box 864, 2381 Risus. Road" },
            new Customer { CustomerName = "Beverly Lawson", Address = "Ap #267-1293 Tellus Road" },
            new Customer { CustomerName = "Octavius M. Page", Address = "P.O. Box 415, 8485 Posuere, Road" },
            new Customer { CustomerName = "Illana Lyons", Address = "Ap #311-7689 At, Ave" },
            new Customer { CustomerName = "Beck P. Cross", Address = "148-5963 Id St." },
            new Customer { CustomerName = "Alice Strong", Address = "P.O. Box 438, 9651 Non St." },
            new Customer { CustomerName = "Brenda Roberts", Address = "9042 Convallis Street" },
            new Customer { CustomerName = "Brooke O. Dunlap", Address = "Ap #704-2500 Dictum. Rd." },
            new Customer { CustomerName = "Caesar I. Chambers", Address = "P.O. Box 344, 3592 Convallis Av." },
            new Customer { CustomerName = "Dorothy Lloyd", Address = "529-3123 Justo. Av." },
            new Customer { CustomerName = "Tatum V. Bowen", Address = "6908 Risus. Rd." },
            new Customer { CustomerName = "Daria Guy", Address = "Ap #316-6613 Fermentum Street" },
            new Customer { CustomerName = "Ryder F. Gamble", Address = "8443 Luctus St." },
            new Customer { CustomerName = "Melanie T. Humphrey", Address = "9571 Arcu. Rd." },
            new Customer { CustomerName = "Benjamin Fuentes", Address = "Ap #272-4054 Tincidunt St." },
            new Customer { CustomerName = "Gisela Riddle", Address = "Ap #280-6233 Magna. Ave" },
            new Customer { CustomerName = "Risa Blair", Address = "366-1489 Pede. Rd." },
            new Customer { CustomerName = "Lamar V. Herman", Address = "Ap #883-6658 Sed St." },
            new Customer { CustomerName = "Sierra Hayden", Address = "871-5786 Eros. Avenue" },
            new Customer { CustomerName = "Mona Barron", Address = "407-6395 Vestibulum Av." },
            new Customer { CustomerName = "Nelle J. Hyde", Address = "690-312 Et Road" },
            new Customer { CustomerName = "Sophia S. Donovan", Address = "9665 Egestas Street" },
            new Customer { CustomerName = "Brent Hyde", Address = "179-4068 Donec St." },
            new Customer { CustomerName = "Gary Hodges", Address = "P.O. Box 857, 2408 Nascetur St." },
            new Customer { CustomerName = "Nell S. Kelley", Address = "Ap #570-516 Ligula Rd." },
            new Customer { CustomerName = "Amy Hewitt", Address = "330-5636 Inceptos Road" },
            new Customer { CustomerName = "Ira L. Thompson", Address = "720-4007 Non Road" },
            new Customer { CustomerName = "Sacha X. George", Address = "Ap #869-4814 Id Av." },
            new Customer { CustomerName = "Ann Z. Hobbs", Address = "P.O. Box 227, 575 Dolor Rd." },
            new Customer { CustomerName = "Kevin Chen", Address = "Ap #769-3219 Sagittis Street" },
            new Customer { CustomerName = "James P. Bennett", Address = "P.O. Box 447, 5170 Proin Road" },
            new Customer { CustomerName = "Geoffrey Tyson", Address = "3037 Proin Avenue" },
            new Customer { CustomerName = "Aphrodite A. Trevino", Address = "9228 Sodales Rd." },
            new Customer { CustomerName = "Alexa Davidson", Address = "P.O. Box 515, 5389 Congue. Ave" },
            new Customer { CustomerName = "Knox I. Blair", Address = "Ap #448-4771 Vulputate, St." },
            new Customer { CustomerName = "Eden Rodriguez", Address = "Ap #105-2547 Mollis Ave" },
            new Customer { CustomerName = "Hector W. Gonzales", Address = "P.O. Box 398, 2526 Massa. Road" },
            new Customer { CustomerName = "Rudyard L. Reynolds", Address = "Ap #830-348 Sodales Avenue" },
            new Customer { CustomerName = "Jessamine O. Guy", Address = "162-9284 Hendrerit Avenue" },
            new Customer { CustomerName = "Frances H. Chapman", Address = "264-4099 Fusce Street" },
            new Customer { CustomerName = "Merrill W. Horn", Address = "P.O. Box 379, 514 Proin St." },
            new Customer { CustomerName = "Hanae O. Flowers", Address = "P.O. Box 969, 6925 Molestie Road" },
            new Customer { CustomerName = "Lane Q. Sears", Address = "443-8746 Felis St." },
            new Customer { CustomerName = "Echo H. Meyers", Address = "P.O. Box 626, 149 Risus. Road" },
            new Customer { CustomerName = "Zena Hatfield", Address = "3917 Quisque St." },
            new Customer { CustomerName = "Martena B. Robertson", Address = "P.O. Box 706, 322 Vestibulum Street" },
            new Customer { CustomerName = "Lionel J. Farley", Address = "2284 Vulputate Av." },
            new Customer { CustomerName = "Miriam Frank", Address = "5387 In Ave" },
            new Customer { CustomerName = "Emi C. Ward", Address = "P.O. Box 167, 8846 Vitae Street" },
            new Customer { CustomerName = "Todd X. Maxwell", Address = "706-5890 Vehicula. Road" },
            new Customer { CustomerName = "Joseph I. Sweeney", Address = "637-479 Vitae Av." },
            new Customer { CustomerName = "Shelly Hendricks", Address = "4601 Eget Ave" },
            new Customer { CustomerName = "Cailin O. Larson", Address = "Ap #488-8469 Non St." },
            new Customer { CustomerName = "Nita Wynn", Address = "8972 Suspendisse Avenue" },
            new Customer { CustomerName = "Phelan G. Booker", Address = "Ap #678-6325 Faucibus Rd." },
            new Customer { CustomerName = "Quamar Leach", Address = "P.O. Box 396, 4027 Sit St." },
            new Customer { CustomerName = "Lydia Rosa", Address = "P.O. Box 890, 6518 Dolor Street" },
            new Customer { CustomerName = "Robert E. Stuart", Address = "P.O. Box 141, 637 Malesuada Ave" },
            new Customer { CustomerName = "Petra Moon", Address = "Ap #455-885 Purus, Rd." },
            new Customer { CustomerName = "Myles Zimmerman", Address = "627-1545 Augue St." },
            new Customer { CustomerName = "Tucker Baker", Address = "Ap #339-7718 Justo Ave" },
            new Customer { CustomerName = "Beatrice David", Address = "P.O. Box 631, 8635 Eget Avenue" },
            new Customer { CustomerName = "Angela P. Hewitt", Address = "Ap #483-9692 Magna Road" },
            new Customer { CustomerName = "Pamela X. Rollins", Address = "801 Gravida Ave" },
            new Customer { CustomerName = "Jorden K. Hill", Address = "461-7104 Montes, Street" },
            new Customer { CustomerName = "Driscoll B. Rasmussen", Address = "P.O. Box 174, 2086 Et, Rd." },
            new Customer { CustomerName = "Macaulay Fernandez", Address = "Ap #661-4373 Donec Ave" },
            new Customer { CustomerName = "Colton Ferrell", Address = "7401 Ligula Street" },
            new Customer { CustomerName = "Phillip N. Acosta", Address = "2023 Sem Rd." },
            new Customer { CustomerName = "Ulric Bailey", Address = "597 Ornare Avenue" },
            new Customer { CustomerName = "Courtney D. Boyer", Address = "Ap #724-5162 Fusce Avenue" },
            new Customer { CustomerName = "Haley M. Bates", Address = "876-2714 Interdum. St." },
            new Customer { CustomerName = "Arden Byers", Address = "857-9369 Enim. St." },
            new Customer { CustomerName = "Murphy Nicholson", Address = "Ap #953-3054 Odio, Ave" },
            new Customer { CustomerName = "Timothy J. Buck", Address = "1090 Quis St." },
            new Customer { CustomerName = "Elvis Schmidt", Address = "1685 Duis Ave" }
        };

    }
}