# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='service.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rservice.proto\"9\n\x05Pizza\x12\x10\n\x08toppings\x18\x01 \x03(\t\x12\x0e\n\x06inches\x18\x02 \x01(\x05\x12\x0e\n\x06\x63heese\x18\x03 \x01(\x08\"G\n\x05Order\x12\x16\n\x06pizzas\x18\x01 \x03(\x0b\x32\x06.Pizza\x12\x15\n\rcustomer_name\x18\x02 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x03 \x01(\t\"/\n\x11OrderConfirmation\x12\x1a\n\x12\x65stimated_delivery\x18\x01 \x01(\x03\x32\x39\n\x08Pizzeria\x12-\n\rRegisterOrder\x12\x06.Order\x1a\x12.OrderConfirmation\"\x00\x62\x06proto3'
)




_PIZZA = _descriptor.Descriptor(
  name='Pizza',
  full_name='Pizza',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='toppings', full_name='Pizza.toppings', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='inches', full_name='Pizza.inches', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cheese', full_name='Pizza.cheese', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=74,
)


_ORDER = _descriptor.Descriptor(
  name='Order',
  full_name='Order',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pizzas', full_name='Order.pizzas', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='customer_name', full_name='Order.customer_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='address', full_name='Order.address', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=147,
)


_ORDERCONFIRMATION = _descriptor.Descriptor(
  name='OrderConfirmation',
  full_name='OrderConfirmation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='estimated_delivery', full_name='OrderConfirmation.estimated_delivery', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=149,
  serialized_end=196,
)

_ORDER.fields_by_name['pizzas'].message_type = _PIZZA
DESCRIPTOR.message_types_by_name['Pizza'] = _PIZZA
DESCRIPTOR.message_types_by_name['Order'] = _ORDER
DESCRIPTOR.message_types_by_name['OrderConfirmation'] = _ORDERCONFIRMATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Pizza = _reflection.GeneratedProtocolMessageType('Pizza', (_message.Message,), {
  'DESCRIPTOR' : _PIZZA,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:Pizza)
  })
_sym_db.RegisterMessage(Pizza)

Order = _reflection.GeneratedProtocolMessageType('Order', (_message.Message,), {
  'DESCRIPTOR' : _ORDER,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:Order)
  })
_sym_db.RegisterMessage(Order)

OrderConfirmation = _reflection.GeneratedProtocolMessageType('OrderConfirmation', (_message.Message,), {
  'DESCRIPTOR' : _ORDERCONFIRMATION,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:OrderConfirmation)
  })
_sym_db.RegisterMessage(OrderConfirmation)



_PIZZERIA = _descriptor.ServiceDescriptor(
  name='Pizzeria',
  full_name='Pizzeria',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=198,
  serialized_end=255,
  methods=[
  _descriptor.MethodDescriptor(
    name='RegisterOrder',
    full_name='Pizzeria.RegisterOrder',
    index=0,
    containing_service=None,
    input_type=_ORDER,
    output_type=_ORDERCONFIRMATION,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PIZZERIA)

DESCRIPTOR.services_by_name['Pizzeria'] = _PIZZERIA

# @@protoc_insertion_point(module_scope)
